inventarios/urls.py
from django.conf.urls import patterns, url
from django.views import generic
from inventarios import views

urlpatterns = patterns('',
	(r'^$', views.index),
    #INVENTARIOS FISICOS
    (r'^InventariosFisicos/$', views.invetariosFisicos_View),
    (r'^InventarioFisico/$', views.invetarioFisico_manageView),
    (r'^InventarioFisico/(?P<id>\d+)/', views.invetarioFisico_manageView),
    (r'^InventarioFisico/Delete/(?P<id>\d+)/', views.invetarioFisico_delete),
    #ENTRADAS
    (r'^Entradas/$', views.entradas_View),
    (r'^Entrada/$', views.entrada_manageView),
    (r'^Entrada/(?P<id>\d+)/', views.entrada_manageView),
    (r'^Entrada/Delete/(?P<id>\d+)/', views.entrada_delete),
    #SALIDAS
    (r'^Salidas/$', views.salidas_View),
    (r'^Salida/$', views.salida_manageView),
    (r'^Salida/(?P<id>\d+)/', views.salida_manageView),
    (r'^Salida/Delete/(?P<id>\d+)/', views.salida_delete),
    
)

microsip_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views import generic
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

dajaxice_autodiscover()
import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
	(r'^$', 'main.views.index'),
    #Descomentar esta linea para habilitar inventarios
    #url(r'^inventarios/', include('inventarios.urls', namespace='Inventarios')),
    #url(r'^inventarios/', 'inventarios.views.index'),
    #Descomentar esta linea para habilitar ventas
    url(r'^ventas/', include('ventas.urls', namespace='ventas')),
    #url(r'^ventas/', 'inventarios.views.index'),
    
    url(r'^cuentas_por_pagar/', include('cuentas_por_pagar.urls', namespace='cuentas_por_pagar')),
    #url(r'^cuentas_por_cobrar/', include('cuentas_por_cobrar.urls', namespace='cuentas_por_cobrar')),
    #url(r'^contabilidad/', include('contabilidad.urls', namespace='contabilidad')),
    
    url(r'autocomplete/', include('autocomplete_light.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    #LOGIN
    url(r'^login/$','inventarios.views.ingresar'),
    url(r'^logout/$', 'inventarios.views.logoutUser'),
)

urlpatterns += staticfiles_urlpatterns()

ventas/urls.py
from django.conf.urls import patterns, url
from django.views import generic
from ventas import views

urlpatterns = patterns('',
	(r'^Facturas/$', views.facturas_View),
	(r'^PreferenciasEmpresa/$', views.preferenciasEmpresa_View),
	
	#Plantilla Poliza
	(r'^plantilla_poliza/$', views.plantilla_poliza_manageView),
    (r'^plantilla_poliza/(?P<id>\d+)/', views.plantilla_poliza_manageView),
    (r'^plantilla_poliza/eliminar/(?P<id>\d+)/', views.plantilla_poliza_delete),
)

cuentas_por_cobrar/models.py
#encoding:utf-8
from django.db import models
from datetime import datetime 
from django.db.models.signals import pre_save
from django.core import urlresolvers
from inventarios.models import *

class ConceptoCc(models.Model):
    id                  = models.AutoField(primary_key=True, db_column='CONCEPTO_CC_ID')
    nombre_abrev        = models.CharField(max_length=30, db_column='NOMBRE_ABREV')
    crear_polizas       = models.CharField(default='N', max_length=1, db_column='CREAR_POLIZAS')
    cuenta_contable     = models.CharField(max_length=30, db_column='CUENTA_CONTABLE')
    clave_tipo_poliza   = models.CharField(max_length=1, db_column='TIPO_POLIZA')
    descripcion_poliza  = models.CharField(max_length=200, db_column='DESCRIPCION_POLIZA')

    def __unicode__(self):
        return self.nombre_abrev

    class Meta:
        db_table = u'conceptos_cc'

class DoctosCc(models.Model):
    id                  = models.AutoField(primary_key=True, db_column='DOCTO_CC_ID')
    concepto            = models.ForeignKey(ConceptoCc, db_column='CONCEPTO_CC_ID')
    folio               = models.CharField(max_length=9, db_column='FOLIO')
    naturaleza_concepto = models.CharField(max_length=1, db_column='NATURALEZA_CONCEPTO')
    fecha               = models.DateField(auto_now=True, db_column='FECHA') 
    cliente           	= models.ForeignKey(Cliente, db_column='CLIENTE_ID')
    cancelado           = models.CharField(default='N', max_length=1, db_column='CANCELADO')
    aplicado            = models.CharField(default='S', max_length=1, db_column='APLICADO')
    descripcion         = models.CharField(blank=True, null=True, max_length=200, db_column='DESCRIPCION')
    contabilizado       = models.CharField(default='N', blank=True, null=True, max_length=1, db_column='CONTABILIZADO')
    tipo_cambio         = models.DecimalField(max_digits=18, decimal_places=6, db_column='TIPO_CAMBIO')
    condicion_pago      = models.ForeignKey(CondicionPago, db_column='COND_PAGO_ID')

    def __unicode__(self):
        return u'%s' % self.id

    class Meta:
        db_table = u'doctos_cc'

################################################################
####                                                        ####
####        MODELOS EXTRA A BASE DE DATOS MICROSIP          ####
####                                                        ####
################################################################

class InformacionContable_CC(models.Model):
    condicion_pago_contado  = models.ForeignKey(CondicionPago, blank=True, null=True)

    def __unicode__(self):
        return u'%s'% self.id

class PlantillaPolizas_CC(models.Model):
    nombre  = models.CharField(max_length=200)
    tipo    = models.ForeignKey(ConceptoCc)
    
    def __unicode__(self):
        return u'%s'%self.nombre

class DetallePlantillaPolizas_CC(models.Model):
    TIPOS = (('C', 'Cargo'),('A', 'Abono'),)
    VALOR_TIPOS =(
        ('Compras', 'Compras'),
        ('Proveedores', 'Proveedores'),
        ('Bancos', 'Bancos'),
        ('Fletes', 'Fletes'),
        ('Descuentos', 'Descuentos'),
        ('Devoluciones','Devoluciones'),
        ('Anticipos','Anticipos'),
        ('IVA', 'IVA'),
    )
    VALOR_IVA_TIPOS             = (('A', 'Ambos'),('I', 'Solo IVA'),('0', 'Solo 0%'),)
    VALOR_CONTADO_CREDITO_TIPOS = (('Ambos', 'Ambos'),('Contado', 'Contado'),('Credito', 'Credito'),)

    plantilla_poliza_CC      = models.ForeignKey(PlantillaPolizas_CC)
    cuenta_co               = models.ForeignKey(CuentaCo)
    tipo                    = models.CharField(max_length=2, choices=TIPOS, default='C')
    valor_tipo              = models.CharField(max_length=20, choices=VALOR_TIPOS)
    valor_iva               = models.CharField(max_length=2, choices=VALOR_IVA_TIPOS, default='A')
    valor_contado_credito   = models.CharField(max_length=10, choices=VALOR_CONTADO_CREDITO_TIPOS, default='Ambos')

    def __unicode__(self):
        return u'%s'%self.id

ventas/models.py
from django.db import models
from datetime import datetime 
from django.db.models.signals import pre_save
from django.core import urlresolvers
from inventarios.models import *
class DoctoVe(models.Model):
    id              = models.AutoField(primary_key=True, db_column='DOCTO_VE_ID')
    folio           = models.CharField(max_length=9, db_column='FOLIO')
    fecha           = models.DateField(db_column='FECHA')
    contabilizado   = models.CharField(default='N', max_length=1, db_column='CONTABILIZADO')
    cliente         = models.ForeignKey(Cliente, db_column='CLIENTE_ID')
    descripcion         = models.CharField(blank=True, null=True, max_length=200, db_column='DESCRIPCION')
    tipo            = models.CharField(max_length=1, db_column='TIPO_DOCTO')
    importe_neto    = models.DecimalField(max_digits=15, decimal_places=2, db_column='IMPORTE_NETO')
    total_impuestos = models.DecimalField(max_digits=15, decimal_places=2, db_column='TOTAL_IMPUESTOS')
    moneda          = models.ForeignKey(Moneda, db_column='MONEDA_ID')
    tipo_cambio     = models.DecimalField(max_digits=18, decimal_places=6, db_column='TIPO_CAMBIO')
    estado          = models.CharField(max_length=1, db_column='ESTATUS')
    condicion_pago  = models.ForeignKey(CondicionPago, db_column='COND_PAGO_ID')
    
    #almacen = models.ForeignKey(Almacenes, db_column='ALMACEN_ID')
    #condicion_pago = models.ForeignKey(CondicionesPago, on_delete= models.SET_NULL, blank=True, null=True, db_column='COND_PAGO_ID')
    def __unicode__(self):
        return u'%s' % self.id
    class Meta:
        db_table = u'doctos_ve'

class DoctoVeDet(models.Model):
    id = models.AutoField(primary_key=True, db_column='DOCTO_VE_DET_ID')
    docto_ve            = models.ForeignKey(DoctoVe, on_delete= models.SET_NULL, blank=True, null=True, db_column='DOCTO_VE_ID')
    articulo            = models.ForeignKey(Articulos, on_delete= models.SET_NULL, blank=True, null=True, db_column='ARTICULO_ID')
    unidades            = models.DecimalField(max_digits=18, decimal_places=5, db_column='UNIDADES')
    precio_unitario     = models.DecimalField(max_digits=18, decimal_places=6, db_column='PRECIO_UNITARIO')
    porcentaje_decuento = models.DecimalField(max_digits=9, decimal_places=6, db_column='PCTJE_DSCTO')
    precio_total_neto   = models.DecimalField(max_digits=15, decimal_places=2, db_column='PRECIO_TOTAL_NETO')

    class Meta:
        db_table = u'doctos_ve_det'

class DoctoVeLigas(models.Model):
    id          = models.AutoField(primary_key=True, db_column='DOCTO_VE_LIGA_ID')
    factura     = models.ForeignKey(DoctoVe, db_column='DOCTO_VE_FTE_ID', related_name='factura')
    devolucion  = models.ForeignKey(DoctoVe, db_column='DOCTO_VE_DEST_ID', related_name='devolucion')

    class Meta:
        db_table = u'doctos_ve_ligas'
        
class LibresFacturasV(models.Model):
    id            = models.AutoField(primary_key=True, db_column='DOCTO_VE_ID')
    segmento_1    = models.CharField(max_length=99, db_column='SEGMENTO_1')
    segmento_2    = models.CharField(max_length=99, db_column='SEGMENTO_2')
    segmento_3    = models.CharField(max_length=99, db_column='SEGMENTO_3')
    segmento_4    = models.CharField(max_length=99, db_column='SEGMENTO_4')
    segmento_5    = models.CharField(max_length=99, db_column='SEGMENTO_5')
    
    def __unicode__(self):
        return u'%s' % self.id
    class Meta:
        db_table = u'libres_fac_ve'

class LibresDevFacV(models.Model):
    id            = models.AutoField(primary_key=True, db_column='DOCTO_VE_ID')
    segmento_1    = models.CharField(max_length=99, db_column='SEGMENTO_1')
    segmento_2    = models.CharField(max_length=99, db_column='SEGMENTO_2')
    segmento_3    = models.CharField(max_length=99, db_column='SEGMENTO_3')
    segmento_4    = models.CharField(max_length=99, db_column='SEGMENTO_4')
    segmento_5    = models.CharField(max_length=99, db_column='SEGMENTO_5')
    
    def __unicode__(self):
        return u'%s' % self.id
    class Meta:
        db_table = u'libres_devfac_ve'

################################################################
####                                                        ####
####        MODELOS EXTRA A BASE DE DATOS MICROSIP          ####
####                                                        ####
################################################################

class InformacionContable_V(models.Model):
    tipo_poliza_ve          = models.ForeignKey(TipoPoliza, blank=True, null=True, related_name='tipo_poliza_ve')
    tipo_poliza_dev         = models.ForeignKey(TipoPoliza, blank=True, null=True, related_name='tipo_poliza_dev')
    condicion_pago_contado  = models.ForeignKey(CondicionPago, blank=True, null=True)
    depto_general_cont      = models.ForeignKey(DeptoCo)

    def __unicode__(self):
        return u'%s'% self.id

class PlantillaPolizas_V(models.Model):
    nombre  = models.CharField(max_length=200)
    TIPOS   = (('F', 'Facturas'),('D', 'Devoluciones'),)
    tipo    = models.CharField(max_length=2, choices=TIPOS, default='F')

    def __unicode__(self):
        return u'%s'%self.nombre

class DetallePlantillaPolizas_V(models.Model):
    TIPOS = (('C', 'Cargo'),('A', 'Abono'),)
    VALOR_TIPOS =(
        ('Ventas', 'Ventas'),
        ('Clientes', 'Clientes'),
        ('Bancos', 'Bancos'),
        ('Descuentos', 'Descuentos'),
        ('Devoluciones','Devoluciones'),
        ('IVA', 'IVA'),
        ('Segmento_1', 'Segmento 1'),
        ('Segmento_2', 'Segmento 2'),
        ('Segmento_3', 'Segmento 3'),
        ('Segmento_4', 'Segmento 4'),
        ('Segmento_5', 'Segmento 5'),
    )
    VALOR_IVA_TIPOS             = (('A', 'Ambos'),('I', 'Solo IVA'),('0', 'Solo 0%'),)
    VALOR_CONTADO_CREDITO_TIPOS = (('Ambos', 'Ambos'),('Contado', 'Contado'),('Credito', 'Credito'),)

    posicion                = models.CharField(max_length=2)
    plantilla_poliza_v      = models.ForeignKey(PlantillaPolizas_V)
    cuenta_co               = models.ForeignKey(CuentaCo)
    tipo                    = models.CharField(max_length=2, choices=TIPOS, default='C')
    asiento_ingora          = models.CharField(max_length=2, blank=True, null=True)
    valor_tipo              = models.CharField(max_length=20, choices=VALOR_TIPOS)
    valor_iva               = models.CharField(max_length=2, choices=VALOR_IVA_TIPOS, default='A')
    valor_contado_credito   = models.CharField(max_length=10, choices=VALOR_CONTADO_CREDITO_TIPOS, default='Ambos')

    def __unicode__(self):
        return u'%s'%self.id

inventarios/forms.py
#encoding:utf-8
from django import forms

import autocomplete_light

from inventarios.models import *
from django.contrib.auth.models import User
from django.forms.models import BaseInlineFormSet, inlineformset_factory
     
class DoctosInManageForm(forms.ModelForm):
	file_inventario = forms.CharField(widget=forms.FileInput, required = False)
	
	class Meta:
		model = DoctosIn
		exclude = (
			'cancelado',
			'aplicado',
			'forma_emitida',
			'contabilizado',
			'sistema_origen',
			'naturaleza_concepto',
			'usuario_creador',
			'fechahora_creacion',
			'usuario_ult_modif',
			'fechahora_ult_modif',
			)

class DoctosInDetManageForm(forms.ModelForm):
	class Meta:
		widgets = autocomplete_light.get_widgets_dict(DoctosInDet)
		model = DoctosInDet
		exclude = (
			'tipo_movto',
			'almacen',
			'concepto',
			'metodo_costeo',
			'rol',
			'cancelado',
			'aplicado',
			'costeo_pend',
			'pedimento_pend',
			'fecha',)

class DoctosInvfisManageForm(forms.ModelForm):
	file_inventario = forms.CharField(widget=forms.FileInput, required = False)
	
	class Meta:
		model = DoctosInvfis
		exclude = (
			'cancelado',
			'aplicado',
			'usuario_creador',
			'fechahora_creacion',
			'usuario_aut_creacion',
			'usuario_ult_modif',
			'fechahora_ult_modif',
			'usuario_aut_modif',
			)

class DoctosInvfisDetManageForm(forms.ModelForm):
	class Meta:
		widgets = autocomplete_light.get_widgets_dict(DoctosInvfisDet)
		model 	= DoctosInvfisDet
		exclude = (
			'claveArticulo',
			)

def doctoIn_items_formset(form, formset = BaseInlineFormSet, **kwargs):
	return inlineformset_factory(DoctosIn, DoctosInDet, form, formset, **kwargs)

def inventarioFisico_items_formset(form, formset = BaseInlineFormSet, **kwargs):
	return inlineformset_factory(DoctosInvfis, DoctosInvfisDet, form, formset, **kwargs)

ventas/forms.py
#encoding:utf-8
from django import forms

import autocomplete_light

from ventas.models import *
from django.contrib.auth.models import User
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from inventarios.models import *

class InformacionContableManageForm(forms.ModelForm):
	tipo_poliza_ve 			= forms.ModelChoiceField(queryset= TipoPoliza.objects.all(), required=True)
	condicion_pago_contado 	= forms.ModelChoiceField(queryset= CondicionPago.objects.all(), required=True)
	
	class Meta:
		model = InformacionContable_V

class GenerarPolizasManageForm(forms.Form):
	fecha_ini 				= forms.DateField()
	fecha_fin 				= forms.DateField()
	ignorar_documentos_cont 	= forms.BooleanField(required=False, initial=True)
	CREAR_POR = (
	    ('Documento', 'Documento'),
	    ('Dia', 'Dia'),
	    ('Periodo', 'Periodo'),
	)
	crear_polizas_por 		= forms.ChoiceField(choices=CREAR_POR)

	plantilla 	= forms.ModelChoiceField(queryset= PlantillaPolizas_V.objects.filter(tipo='F'), required=False)
	plantilla_2 = forms.ModelChoiceField(queryset= PlantillaPolizas_V.objects.filter(tipo='D'), required=False)
	descripcion = forms.CharField(max_length=100, required=False)

	CREAR_DE = (
		('', '---------------'),
	    ('F', 'Facturas'),
	    ('D', 'Devoluciones'),
	    ('FD', 'Facturas y Devoluciones'),
	)
	crear_polizas_de 		= forms.ChoiceField(choices=CREAR_DE)

class PlantillaPolizaManageForm(forms.ModelForm):
	class Meta:
		model = PlantillaPolizas_V

class ConceptoPlantillaPolizaManageForm(forms.ModelForm):
	posicion  		=  forms.RegexField(regex=r'^(?:\+|-)?\d+$', widget=forms.TextInput(attrs={'class':'span1',}), required= True)
	cuenta_co 		= forms.ModelChoiceField(queryset=CuentaCo.objects.all().order_by('cuenta'), required=True)
	asiento_ingora 	= forms.RegexField(regex=r'^(?:\+|-)?\d+$', widget=forms.TextInput(attrs={'class':'span1'}), required= False)

	
	class Meta:
		model = DetallePlantillaPolizas_V

def PlantillaPoliza_items_formset(form, formset = BaseInlineFormSet, **kwargs):
	return inlineformset_factory(PlantillaPolizas_V, DetallePlantillaPolizas_V, form, formset, **kwargs)

inventarios/templates/Salidas/salida.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock %}

<!-- CSS Code -->
{% block style_css %}
<style type="text/css">
  .delete-row {
    margin-left:5px;
  }
</style>

<link rel='stylesheet' href='{{STATIC_URL}}css/redmond/jquery-ui-1.8.23.custom.css'/>

{% endblock %}

<!-- JavaScript Code -->
{% block js_code %}
<script type="text/javascript">
    // Define this so we don't have to bother with the admin jsi18n stuff:
    function gettext(msgid) { return msgid; }
</script>
<script src='{{STATIC_URL}}js/jquery.formset.js'></script>
<script type="text/javascript">
$(function() {
  $('#id_doctosIn_table tbody tr').formset({
    prefix: '{{ formset.prefix }}',
    addCssClass:'btn btn-success',
    addText:'Nuevo Articulo',
    deleteText:'',
  });
});
</script>

{% endblock %}
{% block breadcrumb %}{{ block.super }} <a href="/Salidas/">Salidas</a> > Salida{% endblock %}
{% block content %}
<form method="post" class="form-horizontal" action="" width="300px"  enctype='multipart/form-data'>
  <div class="form-actions mainmenu">
    <input type="submit" class="btn btn-primary" value="Guardar y Salir" />
  </div>
  {% csrf_token %}
  
    {{ Salida_form.errors }}
  
   <div class="control-group">
    <label class="control-label" for="id_folio">Folio</label>
    <div class="controls">
      {{ Salida_form.folio }} 
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="id_descripcion">Descripcion</label>
    <div class="controls">
      {{ Salida_form.descripcion }} 
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="id_concepto">Cocepto</label>
    <div class="controls">
      {{ Salida_form.concepto }}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="id_almacen">Almacen</label>
    <div class="controls">
      {{ Salida_form.almacen }}
    </div>
  </div>
  {{ formset.total_form_count }} Articulos
  {% if message %}
  <div class="alert alert-block alert-error fade in">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4 class="alert-heading">Oh NO! Ocurio un error!</h4>
    <p>{{ message }}</p>
  </div>
  {% endif %}
  <hr>
  {% ifequal Salida_form.folio.value  '' %}
    <a href="{{STATIC_URL}}plantilla_inventarioFisico.xlsx">Descargar plantilla</a>
    <br>
    Agregar campos desde archivo de excel: {{ Salida_form.file_inventario }}<input type="submit" name='excel' class="btn btn-primary" value="Cargar" />
  {% endifequal %}
  
  <div id="doctosIn_data">
    <fieldset>
      <table class="table tableCell table-hover" id="id_doctosIn_table" border="0" cellpadding="0" cellspacing="5">
        <thead>
          <tr>
            <th>Articulo</th>
            <th>Unidades</th>
            <th>Costo Unitario</th>
            <th>Costo Total</th>
          </tr>
        </thead>
        <tbody>
          {% for form in formset.forms %}
          <tr id="{{ form.prefix }}-row" class="form-container">
            {{ form.errors }}
            <td>{% if form.instance.pk %}{{ form.DELETE }}{% endif %}
            	{{ form.articulo }}</td>
            <td>{{ form.unidades }}
              {% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
            </td>
            <td>{{ form.costo_unitario }}</td>
            <td>{{ form.costo_total }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </fieldset>
    {{ formset.management_form }}
  </div>
  {% if message %}
  <div class="alert alert-block alert-error fade in">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4 class="alert-heading">Oh NO! Ocurio un error!</h4>
    <p>{{ message }}</p>
  </div>
  {% endif %}
  <div class="form-actions mainmenu">
    <input type="submit" class="btn btn-primary" value="Guardar y Salir" />
  </div>
</form>

{% include 'autocomplete_light/static.html' %}
{% endblock %}

inventarios/templates/Salidas/salidas.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock %}

<!-- CSS Code -->
{% block style_css %}{% endblock %}

<!-- JavaScript Code -->
{% block js_code %}
{% endblock %}

{% block breadcrumb %}{{ block.super }} salidas {% endblock %}
{% block content %}
<div class="form-actions mainmenu">
  <a class="btn btn-success" href="/inventarios/Salida/">Nueva</a>
</div>
<table class="table tableCell table-hover">
    <tr>
      <th>ID</th>
      <th>FOLIO</th>
      <th>FECHA</th>
      <th>DESCRIPCION</th>
      <th>APLICADO</th>
      <th>OPCIONES</th>
    </tr>
    {% for salida in salidas%}
    <div id="myModal{{ salida.id}}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="myModalLabel">Seguro que Deseas Eliminar</h3>
      </div>
      <div class="modal-body">
        <h4>Al eliminar la salida con el folio: {{ salida.folio }}</h4>
        <p style="color:red;">Ya no sera posible recuperar los datos del inventario</p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancelar</button>
        <a href="/inventarios/Salida/Delete/{{ salida.id }}/" class="btn btn-primary">Estoy Seguro</a>
      </div>
    </div>
    <tr>
      <td>
        <a href="/inventarios/Salida/{{ salida.id }}/">{{ salida.id }}</a>
      </td>
      <td>{{ salida.folio }}</td>
      <td>{{ salida.fecha }}</td>
      <td>{{ salida.descripcion }}</td>
      <td>{{ salida.aplicado }}</td>
      <td style="text-align:center;">
        <a href='#myModal{{ salida.id}}' data-toggle="modal" class="btn btn-mini btn-danger"><i class="icon-trash"></i></a>
      </td>
    </tr>
    {% endfor %}

    <div class="pagination pagination-mini mainmenu">
      <ul>
        {% if salidas.has_previous %}
        <li><a href="?page={{ salidas.previous_page_number }}">Anterior</a></li>
        {% else %}
        <li class="disabled"><a href="#">Anterior</a></li>
        {% endif %}
        <li class="disabled"><a href="#">Pagina {{ salidas.number }} de {{ salidas.paginator.num_pages }}.</a></li>
        {% if salidas.has_next %}
        <li><a href="?page={{ salidas.next_page_number }}">Siguiente</a></li>
        {% else %}
        <li class="disabled"><a href="#">Siguiente</a></li>
        {% endif %} 
      </ul>
    </div>
</table>
<br>
{% endblock %}